language: rust

rust:
  - stable
  - beta
  - nightly

jobs:
  include:
    - stage: lint
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all -- --deny clippy::all

    - stage: format
      rust: nightly
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
